#!/usr/bin/env python3
"""Exports data/newmar_email_ecosystem.db into assets/data.js for the dashboard.

Run this whenever the source .db is refreshed:
    python3 scripts/export_data.py
"""
import json
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _period_utils import sorted_periods  # noqa: E402

DB_PATH = ROOT / "data" / "newmar_email_ecosystem.db"
OUT_PATH = ROOT / "assets" / "data.js"


def rows_as_dicts(cur, table, order_by=None):
    sql = f"SELECT * FROM {table}"
    if order_by:
        sql += f" ORDER BY {order_by}"
    cur.execute(sql)
    cols = [d[0] for d in cur.description]
    return [dict(zip(cols, row)) for row in cur.fetchall()]


def main():
    con = sqlite3.connect(DB_PATH)
    cur = con.cursor()

    cur.execute("SELECT DISTINCT period_label FROM email_performance_by_period")
    period_order = sorted_periods(r[0] for r in cur.fetchall())

    data = {
        "period_order": period_order,
        "workflows": rows_as_dicts(cur, "workflows", "workflow_name"),
        "suppression_lists": rows_as_dicts(cur, "suppression_lists", "list_id"),
        "workflow_suppression_map": rows_as_dicts(cur, "workflow_suppression_map"),
        "program_level_metrics": rows_as_dicts(cur, "program_level_metrics"),
        "workflow_performance_by_period": rows_as_dicts(
            cur, "workflow_performance_by_period"
        ),
        "email_performance_by_period": rows_as_dicts(
            cur, "email_performance_by_period"
        ),
        "email_workflow_classification": rows_as_dicts(
            cur, "email_workflow_classification"
        ),
        "workflow_enrollment_snapshot": rows_as_dicts(
            cur, "workflow_enrollment_snapshot"
        ),
        "aimbase_leads_delivered_to_dealers": rows_as_dicts(
            cur, "aimbase_leads_delivered_to_dealers"
        ),
        "june_2026_report_kpis": rows_as_dicts(cur, "june_2026_report_kpis"),
    }

    con.close()

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    js = "// Auto-generated by scripts/export_data.py — do not edit by hand.\n"
    js += "window.NEWMAR_DATA = " + json.dumps(data, indent=2) + ";\n"
    OUT_PATH.write_text(js)
    print(f"Wrote {OUT_PATH} ({OUT_PATH.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
